### ISSUE TITLE
django 1.7 support

### ISSUE THREAD

**Issue by bufke** [antonagestam/collectfast#49]
With 1.7 files will get added to S3 but never updated. This may be an django-storages issue though.

**Comment by aericson** [comment]
@bufke I have succeeded in making it work with 1.7. This might be same problem as yours. My problem was that in settings.py I had the following:

    INSTALLED_APPS = (
         ...
         'django.contrib.staticfiles',
         ...
         'collectfast',
    )

As you can see from:
https://github.com/django/django/blob/1.7.4/django/core/management/__init__.py#L73

Django 1.7 looks up for management commands in reverse order. Which means I ended up with staticfiles's collectstatic instead of collectfast.

Changed the order in INSTALLED_APPS made it work for me.

It's been months since you posted but it might be usefull to someone else.

**Comment by otanner** [comment]
@aericson Thank you. I spent some hours yesterday figuring out why things are acting very weird (partly because server timezone and Django config timezone didn't match and staticfile's collectstatic wasn't working as expected). With this I got things working.

**Comment by antonagestam** [comment]
@aericson @otanner If you get the time, a pull request for updating the documentation is very welcome!

**Comment by antonagestam** [comment]
@bufke Did you manage to solve the original problem? If you get the time it'd be interesting to see if @aericson's solution works for you. I'll close this issue for now.
