### ISSUE TITLE
"Ignored error in Collectfast:"

### ISSUE THREAD

**Issue by jdotjdot** [antonagestam/collectfast#68]
I'm frequently seeing unspecified, hard-to-identify (let alone debug) errors when running `collectstatic` using Collectfast.  Is there any way to get the errors to print so I can find out what's going on?

These occur within my build process on CircleCI, which adds another layer of complexity.

![image](https://cloud.githubusercontent.com/assets/1328961/11915514/af8891e0-a677-11e5-949a-ce7e09ba573e.png)

**Comment by antonagestam** [comment]
It seems there isn't (https://github.com/antonagestam/collectfast/blob/master/collectfast/management/commands/collectstatic.py#L133).

This exception handling could probably be further developed so that setting a flag (or using `settings.DEBUG`?) makes the exception propagate. I think the reasoning I had when writing this was basically that errors in Collectfast should never prevent collectstatic from running in production environments.

Do you perhaps have the time to look into this further?

**Comment by antonagestam** [comment]
@jdotjdot Would you mind helping me out testing the push I just made to fix this? You can install the development version with `pip install git+https://github.com/antonagestam/collectfast.git@dd21a4d5bbb966495b006a5e660108f2bfa2aee5#egg=collectfast`.

**Comment by jdotjdot** [comment]
Ugh I realized I never responded to this... so sorry about that. For what it's worth, I *am* seeing error output in collectfast now.

**Comment by antonagestam** [comment]
@jdotjdot No worries, thanks for the feedback! 🍰
